### ISSUE TITLE
IE

### ISSUE THREAD

**Issue by wshadw** [wshadw/Web-Developing#1]
https://github.com/SKsusha/WEB/issues/1
https://github.com/PozdnyakovE/Web/issues/1

**Comment by SergeyMirvoda** [comment]
Доклад должен быть не больше чем на 10минут.
Написан в html и приложен файлом к этой задаче.
Не позднее понедельника 02.03.2015.

**Comment by wshadw** [comment]
Доклад про браузер Опера
https://github.com/shelljke/web_applications

**Comment by SergeyMirvoda** [comment]
А чего это вы переименовали задачу?

**Comment by SergeyMirvoda** [comment]
У вас был ИЕ. 
А все остальные?

**Comment by wshadw** [comment]
У остальных остался ИЕ, я присоединился к Андрею, на доклад про Оперу
